# pipeline-repo/.github/workflows/deploy.yml
name: Deploy to Cloudflare Worker

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      base_path:
        required: false
        type: string
        default: ""
    secrets:
      CF_API_TOKEN:
        required: true
      CF_ACCOUNT_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      
      - name: Build Project
        run: |
          if [ -n "${{ inputs.base_path }}" ]; then
            npm run build -- --base "${{ inputs.base_path }}"
          else
            npm run build
          fi

      - run: npm install -g wrangler
      - name: Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: wrangler deploy --env ${{ inputs.environment }}
